### PR TITLE
Docs: How to use GraphQL fragments with redwood

### PR DESCRIPTION
**Pull request by dthyresson**
Closes https://github.com/redwoodjs/redwoodjs.com/issues/879

@orta included an example of how to use GraphQL fragments with Redwood in https://github.com/redwoodjs/redwoodjs.com/issues/879

I adapted his example to be closer to the test app and tutorial for reuse fields on a Post fragment.

I think I have the example correct -- it is working in a sample project with the code shows.

Few questions:

1. Still not 100% certain how the VS Code extension works. I had to change the `documents` setting from
```
+  documents: 'packages/app/src/components/**/*.ts'
```

to 

```
+  documents: 'packages/app/src/components/**/*.ts',
```

because I did not have my app setup as he has.

2. I get some sort of ts lint issue when using the fragment:

image

And I cannot figure out how to resolve.

### CODE REVIEW

**Comment by jtoar** [comment]
@dthyresson Reviewing this now. One quick question: I don't see a difference between the two code blocks. Did you mean for the second one to be something like:
```diff
+  documents: 'web/src/components/**/*.ts',
```

**Comment by dthyresson** [comment]
> @dthyresson Reviewing this now. One quick question: I don't see a difference between the two code blocks. Did you mean for the second one to be something like:
> 
> ```diff
> +  documents: 'web/src/components/**/*.ts',
> ```

Ah, it can be simply:

```
documents: 'web/src/components/**/*.ts',
```

**Comment by dthyresson** [comment]
@orta I had a question about:

```
Still not 100% certain how the VS Code extension works. I had to change the documents setting from

+  documents: 'packages/app/src/components/**/*.ts'
to

+  documents: 'packages/app/src/components/**/*.ts',
```

I was not sure what this did and if the config is ok. 

My fragments were working with or without this addition.

Could it be that your fragments are located outside of `web` and if so then you have to configure graphql?

**Comment by dthyresson** [comment]
Also @orta any idea why I have a TS lint issue as seen






and above?

**Comment by orta** [comment]
Check how many copies of graphql-js there are in your tree, I have a feeling I had to use `resolutions` originally

**Comment by orta** [comment]
```diff
+  documents: 'packages/app/src/components/**/*.ts'
```

Is wrong (I used `packages/app/src/components/**/*.tsx`) before:

Screen Shot 2022-01-26 at 5 01 10 PM

After:
Screen Shot 2022-01-26 at 5 06 07 PM

Basically, the graphql extension without this change _only_ uses the generated schema file to understand your schema, but as the fragments live outside of that the extension needs to know where to pick those up

**Comment by dthyresson** [comment]
> fragments live outside of that the extension needs to know where to pick those up

Oh I see now how you use it. I was importing and also using a placeholder as per some of the Apollo fragment examples.

This looks so much nicer. I’ll try. Thanks!

**Comment by orta** [comment]
On a blank project I didn't get the eslint errors?

Screen Shot 2022-01-26 at 5 11 47 PM

**Comment by dthyresson** [comment]
@orta I must be doing something wrong because when I try to do just:

image

I get the error: `Error: Cannot read properties of undefined (reading 'kind')`

image


This is my `Post.tsx` component with the fragment

```ts
import { Link, routes } from '@redwoodjs/router'

export const PostDetailsFragment = gql`
  fragment PostDetails on Post {
    id
    title
    body
  }
`

export const Post = ({ post }) => {
  return (
    <div key={post.id}>
      <Link to={routes.post({ id: post.id })}>
        <h2>{post.title}</h2>
        <p>{post.body}</p>
      </Link>
    </div>
  )
}
```

**Comment by orta** [comment]
I think you need to include the fragment inside the query, it's probably doing a lookup and not finding the fragment

**Comment by dthyresson** [comment]
This should be a guide instead. Closing as still a few details to work out.

**Pull request closed without merging**
