### PR TITLE
Add CLI reference

### PR DESCRIPTION
**Pull request by jtoar**
_related https://github.com/redwoodjs/redwood/issues/322_

This PR adds a CLI reference section. I'm trying to be comprehensive, so this isn't quite done yet, but I'm throwing up a draft PR to 1) get some feedback and 2) see the copy of the site from `netlify/redwoodjs/deploy-preview`.

### CODE REVIEW

**Comment by thedavidprice** [comment]
Woah, this is a monster of thoroughness. My first thought was _oh, boy, too much_, but then I was all 😍It's really really helpful.

But is this too much detail to ship the first version? If you feel like you're getting bogged down, don't hesitate to skim the depth a bit as you go.

**Comment by jtoar** [comment]
Yeah I can definitely prune it to get a first version out. And after doing this for a day, maybe a better strategy is to get yargs kind of nailed down, i.e. all the command/option descriptions, before going for maximum coverage, so we're not making edits to the reference before and after the fact?

I have questions about the formatting too, but I think I'll experiment a little more first.

**Comment by thedavidprice** [comment]
>Yeah I can definitely prune it to get a first version out.

^^ OK. But don't prune what you already have. Just go lighter on detail for the rest if you'd like -- but in this case please stub out sections where text is needed if applicable.

>yargs kind of nailed down, i.e. all the command/option descriptions, before going for maximum coverage,

^^ Yes, this was "hidden" and on the backburner until we figured out how to get multi-depth options' help text to display. One thing you could do is just keep working on this Doc. And where description are missing, add a `- [ ]` markdown ToDo. That would organize and be a way for others to help as needed. Maybe?

**Comment by jtoar** [comment]
> don't prune what you already have. Just go lighter on detail for the rest if you'd like -- but in this case please stub out sections where text is needed if applicable.

> One thing you could do is just keep working on this Doc. And where description are missing, add a - [ ] markdown ToDo. That would organize and be a way for others to help as needed. Maybe?

Got it! And one thing: is there an obvious better way to do tables? Currently doing this:

```
|Argument|Description|
|:-|:-|
|side | Which side to build. The choices are `api` and `web`. The default is both.|
```

Which looks just ok:

table

Is this when I bother people about mdx?

**Comment by thedavidprice** [comment]
If you're using VS Code, search for this extension to at least help you with the tedium:
Markdown All in One `yzhang.markdown-all-in-one`

re: Tables Styling/Display --> there are two elements to this 1) how the rendered Markdown appears on the website and 2) the "functionality" of tables

I'm not sure if we need much of 2, but if you find something in mdx-land that would help us here, please suggest it! (I don't know of anything off the top of my head.)

And for 1, that would be a conversation with Rob about improving the styling of the rendered table. Make sense?

**Comment by jtoar** [comment]
Thank you installed that just now :rocket: , and yes--I'll try to find an example / mock a style I think would be helpful. It's definitely not functionality like you said. I'll see if I can get a little further on my end first with that extension.

**Comment by jtoar** [comment]
I'll read it again tomorrow, but @thedavid @cannikin I think what's there's close to good for a first version? I'd super appreciate feedback on the format and style of writing, and answers to these specific questions:

**Aliases:** I wasn't sure where to display aliases, so I put them in the title: e.g., ## generate (alias g). Better way to do this? Note: I used the aliased command for all examples.

**yarn rw upgrade:** @thedavid what's the criteria for a release candidate? Like release candidate vs canary--the edge is just bleeding a little less?

**Tables:** I use tables for arguments and options, so there's a lot of them. I use html tags, not markdown syntax, because I had to do more granular styling. @rob what do you think of 1) how they look 2) how I did the styling (tailwind where possible and `#code` tags in `markdown.pcss`)? I didn't experiment much with either yet, was just trying to get the information there first.

cli-ref-table

**Sidebar:** I think I added more headings than the sidebar ever wanted? The scrolling's also a little finicky now. @rob thoughts about this many headings?

**yarn rwt fix-bins:** @peterp what's the exact use case for `yarn rwt fix-bins`? 

**yarn rw open:** Is this command just here for completeness?

**App vs Project:** I had to choose between "app" and "project" many times, and will most likely have to many times again, so maybe we can settle this one once and for all? Last I read (can't remember where) you guys preferred project?

Thank you!

**Comment by cannikin** [comment]
Holy cow this is extremely thorough! Amazing work, thank you!

1. I love the table styling.
2. I guess I never tested out the right sidebar with that many items! 😅The left nav scrolls independently of the main content but I must not have added the same combination of styles to get the right one to do the same. If you wanted to try and get that work I'd be eternally grateful, but I understand if you'd rather do literally anything else in the world. haha

**Comment by peterp** [comment]
> yarn rwt fix-bins: @peterp what's the exact use case for yarn rwt fix-bins?

If you're working on Redwood Framework the permissions of the binaries can sometimes get messed up, and this makes them executable again. This command should probably be removed since we added `copy-watch`

> yarn rw open: Is this command just here for completeness?

Yup, I sometimes use it when I don't want to reach for my mouse to open a site.

**Comment by jtoar** [comment]
> If you wanted to try and get that work I'd be eternally grateful, but I understand if you'd rather do literally anything else in the world. haha

Haha I'll give it a shot and let you know if I run into trouble! And thanks @peterp :+1:

**Comment by jtoar** [comment]
@cannikin I think I fixed it? I removed the `pointer-events-none` class from the aside in `page.html.template`. This was making it hard to scroll the aside, but was it there for another reason? And I added an aside controller to save the scroll position. I thought this was a necessary for good UX, but let me know what you think. And if you like it, I'd appreciate if you could review the code there when you get a chance! It doesn't seem to be throwing any errors but it could probably be a lot better.

**Comment by cannikin** [comment]
Looks good to me! Is this ready to go @thedavidprice?

**Comment by thedavidprice** [comment]
@jtoar this is just a monster doc addition. 🔥Thank you _so_. _much_. for taking the time. This one was really needed and will be so helpful.

My _only_ question is about `redwood-tools`. The structure of this document has the unintentional effect of 1) **burying** the command + text, i.e. hard to find, and 2) **not** making it clear it's a separate command and for a different use-case.

I don't have a strongly preferred answer to fix this. But **what if we pull the RWT section out of this document entirely and:**
1. Add it as a section to the Framework [CONTRIBUTING](https://github.com/redwoodjs/redwood/blob/master/CONTRIBUTING.md) 
2. In the introduction to this document, make it a bit more obvious there are two distinct commands and that this doc covers the `redwood|rw` command, and...
3. ...add a link to the applicable section of the CONTRIBUTING, e.g. something like
```markdown
The Redwood CLI has two entry-point commands: 
1. **redwood** (alias rw), which is for developing an application, and 
2. **redwood-tools** (alias rwt), which is for contributing to the framework 

This CLI document covers the `redwood` command options.

For `redwood-tools` options, see --LINK TO CONTRIBUTING--.
``` 
4. Still keep the the initial header for `## redwood-tools` in this document, but instead of listing options, also refer them to the CONTRIBUTING. E.g. something like:
```markdown
## redwood-tools (alias rwt)
Redwood's companion CLI development tool. You'll be using this if you're contributing to Redwood. For information about using this command and available options, see this section of `[Redwood's Contributing guide](add link)`.
```

Thoughts?

**Comment by jtoar** [comment]
Of course! And 100% for those changes. It's consistent with the developing-on-the-website, contributing-in-the-repo doc division.

**One (probably trivial) question**: should I still list the `## redwood-tools` initial header at the very end? Or should it take its rightful place in the alphabetical order now that it's not a section divider?

**Comment by thedavidprice** [comment]
Coolio. Let's move forward with that plan. 

One addition to the steps --> from CONTRIBUTING.md, **add a link** to the rwjs.com CLI document as well. So referencing well from either context. Make sense?

>One (probably trivial) question: should I still list the ## redwood-tools initial header at the very end? Or should it take its rightful place in the alphabetical order now that it's not a section divider?

^^ Great catch. I think alphabetical is the way to go.

**Comment by jtoar** [comment]
> One addition to the steps --> from CONTRIBUTING.md, add a link to the rwjs.com CLI document as well. So referencing well from either context. Make sense?

Yep; I'll do that now. I'm also linking to a `#Reference` section in the Contributing guide that doesn't exit yet but will soon.

Barring any changes, this one's good to go. :+1: 

Links to the sections that changed:

- [# Command Line Interface](https://deploy-preview-129--redwoodjs.netlify.app/reference/command-line-interface#command-line-interface)
- [## redwood-tools section](https://deploy-preview-129--redwoodjs.netlify.app/reference/command-line-interface#redwood-tools-alias-rwt)

**Comment by thedavidprice** [comment]
🤘🎸🗿 <-- all the "rocks" I could find.

THANKS!!

**Pull request merged**
