### PR TITLE
Copy over and rename/reorder files

### PR DESCRIPTION
**Pull request by jtoar**
This PR 1) copies over any files that were referenced from the repo and 2) re-names/orders all the files so that they're a) titled after their heading and b) in alphabetical order.

@cannikin Wanted to do this before opening a giant tracking issue / recruiting others. Things will probably get renamed (and then reordered) again after we start work on them and esp. after we target searchability. But at least things will be in order till then!

### CODE REVIEW

**Comment by jtoar** [comment]
Note: make sure we’re not breaking links / provide the redirects if we are.

**Comment by jtoar** [comment]
@cannikin This one's ready. @thedavidprice I changed some of titles and and redirects to match and they're all working. :rocket:

**Comment by jtoar** [comment]
@thedavidprice 

**Authentication & Router Docs:** Got it! Added those for-internal-use-only docs. Are the messages there ok?

**CLI (aka doc title vs menu title):** As far as I can tell, it's currently not possible: we pull the url from the first header, `# whatever this is named`, but I'd be happy to spike this feature in another PR? Or should it be a part of this one?

**Contributing:** On board with this. Is it ok if I make it part of another PR though? I tried to avoid making content changes here and made a tracking issue #156 that'll be all about content post this PR. I added your notes on Contributing to that issue!

**Comment by thedavidprice** [comment]
**Auth/Router:** copy you added is perfect ✅

**CLI:** understood and don't let it hold up this PR. @cannikin is it possible to set a different Menu title that overrides the doc h1?

**Contributing:** sounds like a plan!

Thanks again, Dom 🚀(also, I'm super excited about rockets today)

**Comment by cannikin** [comment]
> @cannikin is it possible to set a different Menu title that overrides the doc h1?

Yep, there's a `title` property you can set in in the list of things to build:

```js
{
  pageBreakAtHeadingDepth: [1],
  url: 'redwoodjs/redwood/README.md',
  title: 'Introduction',
},
```

**Comment by jtoar** [comment]
@thedavidprice Does this look right? https://deploy-preview-155--redwoodjs.netlify.app/docs/cli-commands

The document's titled "Command Line Interface" while the link in the menu on the left is named "CLI Commands".

But I'm going to push back on this a little bit and say that I think having the menu differ from the doc's title is a little confusing not good practice and even if it improves searchability. I'm sure we can do it others ways!

**Comment by thedavidprice** [comment]
Great to know we have the option to set "title". Nice work, RC.

> But I'm going to push back on this a little bit and say that I think having the menu differ from the doc's title is a little confusing not good practice and even if it improves searchability. I'm sure we can do it others ways!

^^ I'd say it depends, but it's definitely a super subjective decision in lieu of search and page analytics + history. At this point, I don't have a hard recommendation and leaning on instinct -- if this strikes you as a disorienting UX, then I defer to you.

However, I'll always prioritize "findability" above all else. When I use doc sites, my pattern is to scan the navigation topics and go straight to Search. In this case, I have no idea if people would actually start the search for "CLI" or "Command Line", but I'm guessing it's one of those two. So just trying to find a way, via search, to get them to the right place via multiple paths. And if we remove "Command Line" from the menu and title, there's nowhere else in the Doc that we use that term. So option 2 --> maybe add to introductory paragraph?

Lastly, I have no idea how Algolia is and can work. So I'm just speaking to general practice. But remember people will also hit our site frequently via a direct link from a Google Search, e.g. ["RedwoodJS CLI"](https://www.google.com/search?source=hp&ei=LDnVXrPMNoTZ-gS2vrjgDQ&q=RedwoodJS+CLI&oq=RedwoodJS+CLI&gs_lcp=CgZwc3ktYWIQAzIFCAAQzQI6BQgAEIMBOgIIADoECAAQCjoECAAQDToGCAAQDRAKOgcIIRAKEKABUNMQWIpIYNNSaANwAHgAgAFmiAGLCZIBBDEzLjKYAQCgAQGqAQdnd3Mtd2l6sAEA&sclient=psy-ab&ved=0ahUKEwizkrW9kOHpAhWErJ4KHTYfDtwQ4dUDCAk&uact=5) and ["RedwoodJS Command Line"](https://www.google.com/search?ei=ODnVXu_sB8bb-wTpz6TgDg&q=RedwoodJS+Command+Line&oq=RedwoodJS+Command+Line&gs_lcp=CgZwc3ktYWIQAzIFCCEQoAEyBQghEKABMgUIIRCrAjIFCCEQqwI6BAgAEEc6BAgAEAo6AggAOgcIIRAKEKABUM7qAliq9gJg-f8CaABwAngAgAGAAYgBhQiSAQQxMS4xmAEAoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwjv6OLCkOHpAhXG7Z4KHeknCewQ4dUDCAw&uact=5)

Lots of words here as I'm just trying to expose my thought process -- hope it helps. But if not, just let me know and I’ll adjust to be more direct. 😉

**Comment by jtoar** [comment]
Totally! And thanks for taking the time to. :pray: I know next to nothing about search, other than that I depend on it for almost everything all the time.

From a UX perspective, I still think it's disorienting. I've just never seen a website that has the nav link be different from the doc's title. Some good-doc websites I'm looking at:

- https://reactjs.org/docs/getting-started.html
- https://tailwindcss.com/
- https://docusaurus.io/docs/en/installation

Actually this one tailwind section does it: https://tailwindcss.com/docs/upgrading-to-v1. So there goes that argument! :sweat_smile: 

At the very least I'm gonna ask if we could defer making a ton of searchability-driven changes to another PR and get this one merged so I can start writing some docs? Unless it's not something we can defer b/c it has to be woven in from the start of doc writing?

Right now the menu's named "CLI Commands" and the doc's titled "Command Line Interface". So we'd be covering that ground!

**Comment by thedavidprice** [comment]
> At the very least I'm gonna ask if we could defer making a ton of searchability-driven changes to another PR and get this one merged so I can start writing some docs!

^^ 100% And, again, I’ll defer to you at this time about keeping Menu + Page Titles the same. Fine by me if you do.

Thanks!

**Comment by jtoar** [comment]
@thedavidprice Thanks! Searchability's super important, so I'll start thinking about it as soon as the content feels a little more solid.

@cannikin I've checked all the redirects. Does this look ok to merge?

**Comment by cannikin** [comment]
YUP

**Pull request merged**
