### PR TITLE
Add db import for services section

### PR DESCRIPTION
**Pull request by ryanmdoyle**
Added the db import and updated description to say no "other" imports were omitted.

Resolves redwoodjs/redwood#812

### CODE REVIEW

**Comment by dthyresson** [comment]
@ryanmdoyle 

Current screenshot and copy:

Screen Shot 2020-09-12 at 13 34 35

```js
    <div class="md:w-3/5 md:pl-4 mt-4 md:mt-0">
      <pre><code class="javascript" data-target="application.code">// api/src/graphql/users.sdl.js
import { db } from 'src/lib/db'

export const schema = gql`
  type User {
    id: Int!
    name: String!
  }
  type Query {
    users: [User]
  }
`

// api/src/services/users/users.js
export const users = () => {
  return db.user.findMany()
}

// web/src/components/UsersCell/UsersCell.js
export const QUERY = gql`
  query USERS {
    users {
      id
      name
    }
  }
`
export const Success = ({ users }) => {
  return JSON.stringify(users)
}
```

Even though the code section looks like a single file, it actually represents three and I think that

```
import { db } from 'src/lib/db'
```

is better suited to be associated with `api/src/services/users/users.js` since that is where the `db` import is used and people won't think it is part of the SDL:

```
// api/src/services/users/users.js
import { db } from 'src/lib/db'

export const users = () => {
  return db.user.findMany()
}
``

**Comment by ryanmdoyle** [comment]
Of course. I'll make the change. Thanks for the guidance!

**Comment by ryanmdoyle** [comment]
@dthyresson I updated the import to be under the comment for the actual services file, so I think it's good!

**Review by dthyresson — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
