### PR TITLE
Fix storybook theming instructions

### PR DESCRIPTION
**Pull request by shilman**
@yannbf and I were looking at the docs and this bit about configuring storybook is wrong. I haven't tested the updated docs, but as a maintainer of Storybook I can confidently say that this change either fixes it or, worst case, makes it less wrong than it was before. Please let me know if you have any q's!

### CODE REVIEW

**Comment by thedavidprice** [comment]
Thank you @shilman and @yannbf I'm looping in @realStandal who did the original work that enabled this config via https://github.com/redwoodjs/redwood/pull/3688

I've also not used this in my projects, so I'll lean into @realStandal for confirmation one way or the other.

The current state of the docs reflect our understanding that any Storybook add-ons (in this case `@storybook/theming`) need to be included in Storybook config. So am I understanding correctly that for the case of `storybook.manager.js` that unecessary because of the imports in `storybook.manager.js`?

**Comment by yannbf** [comment]
> Thank you @shilman and @yannbf I'm looping in @realStandal who did the original work that enabled this config via [redwoodjs/redwood#3688](https://github.com/redwoodjs/redwood/pull/3688)
> 
> I've also not used this in my projects, so I'll lean into @realStandal for confirmation one way or the other.
> 
> The current state of the docs reflect our understanding that any Storybook add-ons (in this case `@storybook/theming`) need to be included in Storybook config. So am I understanding correctly that for the case of `storybook.manager.js` that unecessary because of the imports in `storybook.manager.js`?

Hey @thedavidprice you're right that addons should be registered in the `main.js -> addons` property, however `@storybook/theming` is _not_ an addon. It's a wrapper for emotion that we use for theming our components. It also exports the tokens for light/dark theme which are used in the manager configuration. 

The **manager** controls the behavior and look and feel of the Storybook's UI, while **preview** controls the rendering of the components. This image is pretty helpful to help visualize that:

image

**Comment by realStandal** [comment]
Thank you @shilman @yannbf for the clarification, it was a misunderstanding on my part how `@storybook/theming` was to be included and it's role, past adding it to the project as a dependency.

**Comment by thedavidprice** [comment]
Thanks, everyone! Super helpful clarifications. Merging now 🚀

**Pull request merged**
