### PR TITLE
Update references to index.js -> App.js

### PR DESCRIPTION
**Pull request by cannikin**
Also adds a quick note about how to generate the `index.js` file if you need it.

### CODE REVIEW

**Comment by cannikin** [comment]
@dac09 If you get 30 seconds can you check out the changes here and make sure I described things correctly? THANKS!

**Comment by dac09** [comment]
Think you forgot to commit @cannikin. No text about using `rwt custom-web-index`!

**Comment by dac09** [comment]
Never mind, I'm blind

**Review by dac09 — APPROVED** [review]

**Comment by cannikin** [comment]
image

**Pull request merged**
