### PR TITLE
Update TUTORIAL.md

### PR DESCRIPTION
**Pull request by adriatic**
The sentence:
"That's exactly what layouts do: they wrap your pages in a component that then renders the page as its child" is confusing. 

The component renders the page - which page?

### CODE REVIEW

**Comment by adriatic** [comment]
Correct and easy to understand documentation is absolutely critical

**Comment by cannikin** [comment]
It's been a while since I wrote this but I think the gist was that although the same layout is wrapping multiple pages, it only renders a single page at a time. Reading "renders the pages as its children" implies to me that it's rendering all of them together. What do you think about making the *first* instance of "pages" singular instead:

> That's exactly what layouts do: they wrap a page in a component that then renders the page as its child.

**Comment by adriatic** [comment]
That is precisely what I would have done without the ability to consult the author. I would also add your extended clarification, in order to establish the connection with the graphic

image

Thank you for considering this little detail relevant to spend some time to address it

**Comment by cannikin** [comment]
I've re-written this text and made a more direct reference to the diagram in an upcoming update for 0.25: #549 

I'm going to close this one, thanks for pointing it out!

**Comment by adriatic** [comment]
There is really no need for merging any patches - if anyone, @cannikin knows how to fix this. Thank you Rob.

**Pull request closed without merging**
