### PR TITLE
Recipe: Sending emails and importing service

### PR DESCRIPTION
**Pull request by Tobbe**
This is an attempt at solving #94 and an alternative to #945. Let's compare and see which one would benefit our users the most 🙂

### CODE REVIEW

**Review by cannikin — APPROVED** [review]
Interesting! I like this one as well since it does address the service-within-a-service issue. Unfortunately, not many people will see it unless they want to send an email and find this cookbook. We should probably add a section in the Services page of the docs that talks about composing services to surface it to more folks.

**Comment by Tobbe** [comment]
> it does address the service-within-a-service issue. Unfortunately, not many people will see it

Yeah, I know. I tried to make it a bit more visible by making it a heading that shows up in the RHS nav menu. I've now also added a blurb about it in the top paragraph. Hopefully those two things will make google pick up on it, so if someone does a google search for it they'll find it.

**Comment by Tobbe** [comment]
Got this message from @callingmedic911 

> Both of them are great! If I have to select one, I'd say #949 because it focuses on only sending email and nothing more. With the newsletter example in #945, in comparison, people might expect the whole thing, how to schedule the newsletter, subscription and unsub management (even though you hinted in the last section that there's more to it).
Just my opinion. In any case, both are super helpful for the community.

Thanks to his message I've decided to move forward with this PR, and close the other one

**Comment by Tobbe** [comment]
GitHub CDN FTW!

image

image

image

image

image

**Pull request merged**
