### PR TITLE
Homepage Redesign in Preparation of 1.0

### PR DESCRIPTION
**Pull request by cannikin**
image

Not sure why I didn't add this screenshot when I first posted the PR!

### CODE REVIEW

**Comment by noire-munich** [comment]
Hello @cannikin ,

I'm here per invite from @thedavidprice , I did the following:
```
  git clone https://github.com/redwoodjs/redwoodjs.com.git 
  cd redwoodjs.com
  yarn install
  git checkout rc-new-homepage
  yarn build
  yarn dev
```

Which resulted in:
```
CssSyntaxError: /Workspace/Code/RedwoodjsForks/redwoodjs.com/code/stylesheets/markdown.pcss:137:5: `@apply` cannot be used with `.whitespace-nowrap` because `.whitespace-nowrap` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.whitespace-nowrap` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

  135 | 
  136 |   th:first-child {
> 137 |     @apply rounded-tl-lg whitespace-nowrap;
      |     ^
  138 |   }
  139 | 
```

Eventually it's fixable with a light `yarn update`, I wanted to push a commit but got a 403 on the repo :-\

**Comment by cannikin** [comment]
Make sure you run `yarn install` again after changing to my branch, it upgrades to TailwindCSS 2.0, which is where that new class name comes from (it used to be `.whitespace-no-wrap` but apparently they removed the second dash).

This new homepage isn't ready for primetime yet, what changes/updates are you looking to make?

**Comment by noire-munich** [comment]
Thanks @cannikin it does work.

I don't have plans so to speak, I had layed down some ideas on a figma we can see there: https://community.redwoodjs.com/t/promoting-redwoodjs-follow-up-to-some-points-from-the-19th-feb-contributors-meetup/1864 

@thedavidprice suggests we should open the topic and make it public, I'm wondering if some of those ideas could be worth iterating over or if it was of no interest. Do you have some specs, things contributors could help with?

**Comment by cannikin** [comment]
I'm going to close this and re-open as an Issue

**Comment by cannikin** [comment]
https://github.com/redwoodjs/redwoodjs.com/issues/713

**Pull request closed without merging**
