### PR TITLE
Add CLI Exec Examples

### PR DESCRIPTION
**Pull request by viperfx**
This expands the CLI exec command docs with

- example use cases 
- details background worker example with Faktory

Open to feedback about any other use cases I can expand on. 

I have a syncStripe script - but it would involve adding the prisma schema tables and the script to make sense. So wanted to get feedback on if we feel that's worth adding? 

I also have custom seedScripts but they are rather long as well - so for a short example - not sure it's a good fit.

### CODE REVIEW

**Comment by dthyresson** [comment]
It might be nice to use the logger here instead of console:

```
const { postSignupTask } from '$api/src/lib/tasks'
const faktory = require('faktory-worker')

faktory.register('postSignupTask', async (taskArgs) => {
  await postSignupTask(taskArgs)
})

export default async ({ _args }) => {
  const worker = await faktory
    .work({
      url: process.env.FAKTORY_URL,
    })
    .catch((error) => {
      console.error(`worker failed to start: ${error}`)
      process.exit(1)
    })
  worker.on('fail', ({ _job, error }) => {
    console.error(`worker failed to start: ${error}`)
  })
}
```
<details><summary>Browser metadata</summary>





```
Path:      /docs/cli-commands#background-worker-with-faktory
Browser:   Safari 14.1.2 on Mac OS 10.15.7
Viewport:  1720 x 1335 @1x
Language:  en-us
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-815--redwoodjs.netlify.app%2Fdocs%2Fcli-commands%23background-worker-with-faktory&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1720x1335&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-815--redwoodjs.netlify.app/docs/cli-commands#background-worker-with-faktory) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=615765c04f529f0007625920&commentID=6157809248af4200d3402e96&resolution=resolved)

**Comment by dthyresson** [comment]
But, I don't know if the logger from api is available in scripts -- now that I think on it. But if it ruins a job, that could be useful Especially if logging to Datadog etc.
<details><summary>Browser metadata</summary>





```
Path:      /docs/cli-commands#background-worker-with-faktory
Browser:   Safari 14.1.2 on Mac OS 10.15.7
Viewport:  1720 x 1335 @1x
Language:  en-us
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-815--redwoodjs.netlify.app%2Fdocs%2Fcli-commands%23background-worker-with-faktory&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1720x1335&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-815--redwoodjs.netlify.app/docs/cli-commands#background-worker-with-faktory) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=615765c04f529f0007625920&commentID=615780ea33a9ce00ab7cbf76&resolution=resolved)

**Comment by dthyresson** [comment]
Does this feel more like a Cookbook than a doc?


<details><summary>Browser metadata</summary>





```
Path:      /docs/cli-commands#background-worker-with-faktory
Browser:   Safari 14.1.2 on Mac OS 10.15.7
Viewport:  1720 x 1335 @1x
Language:  en-us
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-815--redwoodjs.netlify.app%2Fdocs%2Fcli-commands%23background-worker-with-faktory&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1720x1335&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-815--redwoodjs.netlify.app/docs/cli-commands#background-worker-with-faktory) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=615765c04f529f0007625920&commentID=6157812116135100d03c9582&resolution=resolved)

**Comment by viperfx** [comment]
@dthyresson yea the logger totally works! Anything inside redwood folders can be shared.

Yea I wasn't sure about where it fit the best.

**Comment by jtoar** [comment]
Thanks @viperfx! I'll take it from here, moving the example to a cookbook and referencing that cookbook from the usage section of the redwood exec CLI.

**Pull request merged**
