### PR TITLE
Add GraphQL client config cookbook

### PR DESCRIPTION
**Pull request by jtoar**
> WIP
>
> https://deploy-preview-563--redwoodjs.netlify.app/cookbook/configuring-your-own-graphql-client

This PR adds a new cookbook "Configuring your own GraphQL Client" which details an example of using the FetchConfigProvider, GraphQLHooksProvider, and React Query to configure a custom GraphQL client.

Resources:
- https://github.com/redwoodjs/redwood/pull/1498
- https://github.com/redwoodjs/redwood/pull/1639
- https://community.redwoodjs.com/t/switch-to-another-graphql-client/1714
- https://community.redwoodjs.com/t/react-query-provider-for-redwood/1709
- https://community.redwoodjs.com/t/redwoodjs-v0-22/1660
- https://community.redwoodjs.com/t/redwood-v0-24-0/1771
- https://github.com/redwoodjs/redwood/issues/1608
- https://github.com/redwoodjs/redwood/issues/1759
- https://www.npmjs.com/package/graphql-request
- https://react-query.tanstack.com/devtools

### CODE REVIEW

**Comment by thedavidprice** [comment]
Nice work @jtoar I know @Tobbe is already in the loop; I do suggest having him help review and finalize this. The article he wrote might make for a nice reference link as well (up to you two to make the call of course).

Thanks!

**Comment by cannikin** [comment]
@jtoar Did you wanna move this to the main repo? Is it still valid? 😬

**Comment by Tobbe** [comment]
Getting all the nuances just right is really difficult. I know what I have works, but I'm pretty sure it's not as good as it could be. A guide would be really helpful.

**Comment by jtoar** [comment]
Closing this for now. I'll try to work this in again when I'm auditing the docs.

**Pull request closed without merging**
