### PR TITLE
makes ref to env vars on web clearer

### PR DESCRIPTION
**Pull request by sarthaktexas**
ref to #735

### CODE REVIEW

**Comment by dthyresson** [comment]
@cannikin As you authored https://github.com/redwoodjs/redwoodjs.com/issues/735 have assigned for your review.

Though, this no now longer explain how to use a personal, local `.env` or how to use the `.defaults.env` though it is somewhat referred to in the above section (see Web).

I think one of the issues is that the `includeEnvironmentVariables = ` is not set to `[]` in the default create redwood app template -- so it is easy to forget to set them in dev ... unless you refer to these docs.

Maybe that setting is added by default?

**Comment by thedavidprice** [comment]
Quick FYI that @cannikin is taking a vacation this week. He'll be back next week. Please don't hesitate to nudge as needed after Aug 18th if you haven't heard from him.

**Review by cannikin — APPROVED** [review]

**Comment by cannikin** [comment]
@dthyresson Good call, should we update CRA to include that in the redwood.toml template? We can add a comment above with a quick explanation as well...

**Comment by sarthaktexas** [comment]
sorry for being dumb, what's CRA? i can totally make a pr to do whatever it is that yall are saying too

**Comment by aidenybai** [comment]
This is very epic of you sarthak.

**Comment by sarthaktexas** [comment]
@cannikin can you make a new issue regarding this?

**Comment by cannikin** [comment]
@sarthaktexas There you go!  👆

**Pull request merged**
