### PR TITLE
Support Qovery as a deployment option

### PR DESCRIPTION
**Pull request by arnaudjnn**
Hi Redwood team,

I added docs on deploying Redwood to Qovery - feedback is welcome.

Arnaud.

### CODE REVIEW

**Comment by dthyresson** [comment]
Hi @arnaudjnn.

Thanks for introducing me to https://www.qovery.com.

One question I have is, does it build the app (web and api sides) like a Vercel or Netlify?

Or when linking to your repo, 

> Now that Qovery is connected to your repo, it will **automatically build and publish your site** any time you push to GitHub.

will one have had to build each side separately ahead of time?

Also, could you point to a RedwoodJS app running or Quovery as an example (maybe an example repo with the configuration like where to set Environment varioables, etc)?

**Review by thedavidprice — CHANGES_REQUESTED** [review]
Hi @arnaudjnn Thanks for this! Excited to learn more and possibly offer first-class, built-in support for Qovery as a deploy target. Looks possible based on your docs.

Could you connect with me by email — I'd like to find time to get a demo and discuss the deploy DX we envision for Redwood. There are several ways forward here. It would be easier to plan if we sync up:
thedavid@thedavidprice.com

**Comment by thedavidprice** [comment]
## Status Update
Had a great meeting with the Qovery team today. We are coordinating to add first-class support as a Redwood deploy target, including `setup` and `deploy` commands. More to come 🚀

**Comment by jtoar** [comment]
Hey @arnaudjnn are you still interested in working on this one / anything I can do to help you get this to the finish line?

**Pull request closed without merging**
