### PR TITLE
Update tutorial /docs/ to /guides/

### PR DESCRIPTION
**Pull request by matthewhembree**
Tutorial: Broken link cleanup. Consistent link format.

### CODE REVIEW

**Comment by matthewhembree** [comment]
Tutorial: Broken link cleanup. Consistent link format. Use relative links (helpful for preview).

**Comment by matthewhembree** [comment]
Not sure why the checks aren't running. Probably because I closed/reopened instead for converting to draft?? Let's try that.

**Comment by matthewhembree** [comment]
> Not sure why the checks aren't running. Probably because I closed/reopened instead for converting to draft?? Let's try that.

Nope, I guess it's a one shot deal. ☹️

**Comment by cannikin** [comment]
Thanks!

**Pull request merged**
