### PR TITLE
doc: add Shadowenv setup command

### PR DESCRIPTION
**Pull request by virtuoushub**
See: https://github.com/redwoodjs/redwood/pull/3499

### CODE REVIEW

**Review by callingmedic911 — COMMENTED** [review]
Nice! I have just added this suggestion to explain potential benefit of using Shadowenv. :)

**Comment by Tobbe** [comment]
As a recent switcher from Windows to Mac, can I ask what the benefit of using shadowenv compared to just defining an alias is in the RW case?

**Comment by callingmedic911** [comment]
> As a recent switcher from Windows to Mac, can I ask what the benefit of using shadowenv compared to just defining an alias is in the RW case?

I'll defer to @virtuoushub for the details but what I gathered is Shadowenv offers aliasing specific to the `cd`ed directory and cleans up after. Which means, you can have multiple RW projects and `rw` command will correspond to the one you're inside.

**Comment by Tobbe** [comment]
> But I think you meant `alias rw="yarn rw"`

Yes, exactly :)  Sorry, I should have specified!

**Comment by virtuoushub** [comment]
> As a recent switcher from Windows to Mac, can I ask what the benefit of using shadowenv compared to just defining an alias is in the RW case?

@Tobbe (cc @callingmedic911 ) Please see: https://github.com/redwoodjs/redwood/pull/1773#issuecomment-789261636 and the comments before for context around the choice of tooling.

**Comment by thedavidprice** [comment]
> But for me, if I just continue using my alias rw="yarn rw", (and alias rwfw="yarn rwfw") what am I missing out on?

@Tobbe Understood. For those who know their shell, that would be simpler. I need to run through the process fully, but this is meant to be a solution that's cross-shell/platform. There may be more steps than I originally understood when this was proposed (way) back in the day.

Lastly, do check out the full documentation for shadowenv. I'm personally very interested in using it to "shadow" env vars per project.

**Comment by virtuoushub** [comment]
Closing this as corresponding PR is also closed: https://github.com/redwoodjs/redwood/pull/3499#issuecomment-966724184

**Pull request closed without merging**
