### PR TITLE
Adds testing documentation

### PR DESCRIPTION
**Pull request by cannikin**
I'm holding up this Rails Guide to testing as my gold standard: https://guides.rubyonrails.org/testing.html 

It describes everything that Rails provides for testing, and how to test all the various parts you would build (models, controllers, jobs). It's crazy thorough and is usually the first place I go if I forget how to write a test for something, even before Google. And most Google queries will return this doc as the first result anyway.

### CODE REVIEW

**Comment by cannikin** [comment]
Trying out some inline code execute with JSFiddle: https://deploy-preview-530--redwoodjs.netlify.app/docs/testing#a-simple-test

**Comment by thedavidprice** [comment]
Nice!

Not sure you need more options, but Docusaurus v2 uses React Live for .mdx:
https://v2.docusaurus.io/docs/markdown-features/#interactive-code-editor

**Review by jtoar — COMMENTED** [review]
@cannikin This is amazing! 🤯 Planning to publish a review on this tomorrow, just takes time to enter changes from my editor into GitHub's code review. Looking at a few vscode extensions... 

For now, consider this my only suggestion.

**Comment by cannikin** [comment]
Thanks! It's only probably half-way done and I haven't done a full run-through to fix flow issues, or grammar and typos. I'd love a review but you might want to wait until after all that so I get a chance to catch all the embarrassing mistakes. :)

**Comment by jtoar** [comment]
@cannikin Sure thing--just let me know

**Comment by cannikin** [comment]
Oh geez, almost up to 6,000 words and I haven't event got into server-side testing yet. 😬

**Comment by cannikin** [comment]
First draft done, 8,000 words. 😬 Let me take a pass through and fix anything glaring and then I'll hit you up @jtoar, probably tomorrow!

**Comment by cannikin** [comment]
Okay @jtoar I think it's ready! 

I did a big refactor on the section headings to get the right nav much easier to browse to a topic.

**Review by jtoar — COMMENTED** [review]
@cannikin I think I could make more edits, particularly to the latter half of the document just because I started at the top and got less and less keen as I was going, but this is a good start, and don't want to hold off reviews any longer. Let me know what you think; a good amount are just "capitalize this" because I feel like @thedavidprice and I have gone back and forth about capitalizing "Redwood nouns" like Cell, Service, etc. I think it's helpful to do so!

**Pull request merged**
