### PR TITLE
Update RBAC cookbook with example of how to protect service with GraphQL directives

### PR DESCRIPTION
**Pull request by jacebenson**
This should solve for #812 .

I updated the How to protect a service section with a SDL a bit of copy before it and then highlighted the updated lines at the bottom.

Here's what it looked like locally.
image

Let me know if there's more I should do

### CODE REVIEW

**Comment by jacebenson** [comment]
Let me know if that changes i made covered the concerns you had @dthyresson

**Review by dthyresson — CHANGES_REQUESTED** [review]
Actually, I think that both techniques apply:

* Protect a service used as a resolver via the GraphQL dierctive
* Protect a service used elsewhere via the current described auth method
* and third, the forthcoming info here on protecting serverless functions https://github.com/redwoodjs/redwoodjs.com/pull/928
*

**Comment by dthyresson** [comment]
@jacebenson i think RBAC has been updated to include this info perhaps? If so we can close

**Comment by jacebenson** [comment]
the SDL isn't there anymore so it's not wrong.  I'm okay with it.

**Pull request closed without merging**
