### PR TITLE
Fix type-check typo and add it to CLI command doc

### PR DESCRIPTION
**Pull request by morganmspencer**
Fix typo: `type-check` vs `typecheck`

### CODE REVIEW

**Comment by morganmspencer** [comment]
Just saw #756 

I'll add in the CLI command as well

**Comment by dthyresson** [comment]
> I'll add in the CLI command as well

Thanks @morganmspencer. Will you address https://github.com/redwoodjs/redwoodjs.com/issues/756 in this PR as well or a separate one?

**Comment by morganmspencer** [comment]
@dthyresson I'll do it in this one if that works

**Comment by morganmspencer** [comment]
@dthyresson just added the CLI command

Closes #756

**Comment by dthyresson** [comment]
LGTM. Thanks!

**Pull request merged**
