### PR TITLE
Add docs for known limitations for RDS Proxy

### PR DESCRIPTION
**Pull request by betocmn**

### CODE REVIEW

**Comment by jtoar** [comment]
@betocmn Thanks for adding this detail! Didn't want to prematurely merge this, but looks good to me&mdash;is this ready to go?

**Comment by betocmn** [comment]
No worries at all, @jtoar. I think it is, but maybe best to wait and see if anyone has some other perspective on this? I've just shared with the community: https://community.redwoodjs.com/t/limitations-using-aws-dbs-with-netlify-functions/967

**Comment by betocmn** [comment]
Hey @jtoar , I've updated with more information after the [discussion](https://community.redwoodjs.com/t/limitations-using-aws-dbs-with-netlify-functions/967) over the community forum and I think it's good to go on my end. Please let me know if you think it needs any changes. Thanks!

**Comment by jtoar** [comment]
@betocmn Thanks for taking a detour through the forum; you added a quality discussion there and its refined counterpart in the docs. Amazing! :rocket:

**Comment by betocmn** [comment]
Ah great to know, mate. But no worries at all, you guys are doing an amazing job and I'm happy to help when I have a chance :)

**Pull request merged**
