### PR TITLE
Update TUTORIAL.md

### PR DESCRIPTION
**Pull request by adriatic**
Changes in the authentication setup (https://redwoodjs.com/tutorial/authentication#authentication-setup)

### CODE REVIEW

**Comment by adriatic** [comment]
While I know relatively a lot about IAM (Identity and Access Management), via SaaS I know nothing about Netflix, so I was pleasantly surprised [Netlify based IAM](https://redwoodjs.com/tutorial/authentication#authentication). Word of caution - please verify my proposed changes

**Comment by adriatic** [comment]
A remaining question: should I recreate this PR there (https://learn.redwoodjs.com)? or some more intensive updates are planned?

**Comment by cannikin** [comment]
Unfortunately you'll have to recreate, there's no longer one giant TUTORIAL.md file in the new repo, it's been broken down by section. I was able to move the issues over cleaning, but the PRs need to get re-created. Sorry about that!

**Comment by adriatic** [comment]
No problem, happy to help, despite obstacles 😄

**Pull request closed without merging**
