### PR TITLE
Add Cypress e2e tests for Tutorial.

### PR DESCRIPTION
**Pull request by peterp**
This adds a way to test "the golden path" which is our tutorial. We'll use `yarn test:tutorial` to run cypress e2e tests.

### CODE REVIEW

**Comment by thedavidprice** [comment]
Ah, I thought we had decided to add this to Framework repo to handle automation there. It doesn't make sense for me to have CI also happening in .com. Anyway, TBD.

Excited about this most of all!

**Comment by cannikin** [comment]
Yeah, even though this is testing the tutorial, the tutorial is actually just text, not code, so I'm not sure it needs to live in this repo...now all of redwood is a dependency of the HTML website? THAT doesn't feel right...

**Comment by thedavidprice** [comment]
Also, I think I need more help getting the dev server process running. Couldn't get things to work initially.

**Comment by peterp** [comment]
Ok, damn, it was in the framework repo, but I guess I misunderstood. Moving it baaaack!

**Comment by peterp** [comment]
> Also, I think I need more help getting the dev server process running. Couldn't get things to work initially.

Details sir, I need them.

**Comment by thedavidprice** [comment]
fwiw: I believe one of the assumed "issues" I was having yesterday was due to the fact this was actually catching the bug introduced by the new messaging bus system. Trial by fire, baby 🚀🚀`*`


`*` 🚀🚀 > 🌈🌈

(You all remember the ol' "double rainbow" meme, right??)

**Pull request merged**
