### PR TITLE
Update & Fix links in TUTORIAL.md

### LINKED ISSUE #541: Tutorial Part 2 *Link* is not working properly
Hi

## I think that **Tutorial Part 2 Link** here: 👇

Image-1

## Is not working properly, Because it is going to `404 Page` as follows: 👇

Image-2

## And it should redirect to the following page link: 👇 

Image-3

## Also these links not working: 👇

Image-4

If it is true, I will be happy to open a PR and fix it.

Thanks

### PR DESCRIPTION
**Pull request by TawfikYasser**
Hi this PR fixes #541 

Link updating:

* Tutorial Part 2
* calling to a third party API
* deploying an app without an API at all
* install Postgres locally?
* guides

in What's Next? -> TUTORIAL.md

I hope this be good.

Thanks

### CODE REVIEW

**Comment by thedavidprice** [comment]
Awesome! I've looped in @cannikin for review.

**Comment by TawfikYasser** [comment]
> Awesome! I've looped in @cannikin for review.

Thanks

**Comment by cannikin** [comment]
So these docs are meant to be read on https://redwoodjs.com and the relative links go to other pages on that site. You've updated these links to point to the *source* docs on GitHub itself, which is not what we want. :) You'll see if you read that section here on the site that the links redirect as expected: https://redwoodjs.com/tutorial/wrapping-up

**Comment by cannikin** [comment]
Hi @TawfikYasser did you see this comment? We appreciate the work you put in here but these files are meant to be compiled into the real site at https://redwoodjs.com/tutorial where the links work as expected.

I'm going to close this but let us know if you have any more questions! :)

**Pull request closed without merging**
