### PR TITLE
Adding note about additional binaryTarget needed for Netlify deploy

### PR DESCRIPTION
**Pull request by mkhbragg**
Issue: https://github.com/redwoodjs/redwoodjs.com/issues/446

### CODE REVIEW

**Comment by cannikin** [comment]
Thank you! Although it looks like Prisma is going to fix this with their 2.11.0 release this'll be helpful for anyone stuck in that windows when it was busted.

**Comment by cannikin** [comment]
Oh snap and is this your first PR with Redwood?? WELCOME! @thedavidprice is on vacation for the next couple of days, but I know he'd want me to give you a rocketship so here you go! 🚀

**Comment by mkhbragg** [comment]
My very own 🚀!!? Thank you @cannikin 😁, the Redwood community sure is nice.

**Comment by thedavidprice** [comment]
This is absolutely the best message thread to come back to after a vacation. 🚀 indeed! 😆

And welcome @mkhbragg! Great to have you as a part of the community.

**Pull request merged**
