### PR TITLE
Tutorial Part II

### PR DESCRIPTION
**Pull request by cannikin**
Current blockers:

* https://github.com/redwoodjs/redwood/issues/1374
* https://github.com/redwoodjs/redwood/issues/1299

### CODE REVIEW

**Comment by ajcwebdev** [comment]
You're missing an `rw` in the `yarn rw dev` command for the prerequisites section right at the beginning.

**Comment by ajcwebdev** [comment]
I'm getting failing tests after following the first set of commands. Page seems to load with the blog posts fine:

Screen Shot 2020-10-20 at 9 52 42 PM

Screen Shot 2020-10-20 at 9 48 29 PM

Screen Shot 2020-10-20 at 9 48 42 PM

Screen Shot 2020-10-20 at 9 49 01 PM

Screen Shot 2020-10-20 at 9 49 07 PM

It looks like it's trying to find the blog posts contained in the `BlogPostsCell.mock.js` instead of the blog posts contained in the `seeds.js` file.

Screen Shot 2020-10-20 at 9 55 31 PM

Screen Shot 2020-10-20 at 9 55 55 PM

Not sure if this is an error in the tutorial or if I made some sort of mistake while seeding the data or running the tests, I think I followed the instructions exactly as describe.

**Comment by cannikin** [comment]
> I'm getting failing tests after following the first set of commands. Page seems to load with the blog posts fine:

Try now, I had a couple local commits that I hadn't pushed up yet!

**Comment by ajcwebdev** [comment]
Screen Shot 2020-10-21 at 12 45 50 AM

Yeah that did the trick.

**Comment by guledali** [comment]
@cannikin Don't think there should be some tutorial on how to do testing in the `api/src/services`

**Comment by cannikin** [comment]
@guledali I'm actually working on the section where I test the services right now!

**Comment by ajcwebdev** [comment]
When I'm doing the initial setup commands my terminal is hanging on the `yarn rw db seed` command:

Screen Shot 2020-11-05 at 1 57 57 PM

If I hit ^C and then start the dev server everything still shows up so it looks like the seed command is actually working. Is this happening to anyone else?

**Comment by cannikin** [comment]
> When I'm doing the initial setup commands my terminal is hanging on the yarn rw db seed command:

Yup, happens for me too. I think @thedavidprice thought this might have happened as a result of something Prisma did but neither of us have had a chance to look into it. :(

**Comment by ajcwebdev** [comment]
Okay thanks for the heads up, I'm actually in the Prisma Migrate Early Access program so maybe I could try to file a bug report through there.

**Comment by cannikin** [comment]
My first attempt was going to be just littering the seeds.js file with `console.log()` statements to see where it gets stuck. Presumably AFTER the records are inserted, but then it's the end of the function so I don't know what it would be getting stuck on!

**Comment by thedavidprice** [comment]
YES 🚀🚀

**Pull request merged**
